.phony all

all: tcp by udp server, tcp by udp client

tcp by udp server:
	 g++ -o server tcp\ client&server/server.cpp -lpthread

tcp by udp client:
	 g++ -o client tcp\ client&server/client.cpp -lpthread

clean:
	 rm -f server client